export const dummyQueries = [
  {
    name: "Product Inventory",
    query: `SELECT productID, productName, supplierID, categoryID, quantityPerUnit, 
               unitPrice, unitsInStock, unitsOnOrder, reorderLevel, discontinued 
        FROM products;`,
    results: [
      {
        productID: 1,
        productName: "Chai",
        supplierID: 1,
        categoryID: 1,
        quantityPerUnit: "10 boxes x 20 bags",
        unitPrice: 18,
        unitsInStock: 39,
        unitsOnOrder: 0,
        reorderLevel: 10,
        discontinued: 0,
      },
      {
        productID: 2,
        productName: "Chang",
        supplierID: 1,
        categoryID: 1,
        quantityPerUnit: "24 - 12 oz bottles",
        unitPrice: 19,
        unitsInStock: 17,
        unitsOnOrder: 40,
        reorderLevel: 25,
        discontinued: 0,
      },
      {
        productID: 3,
        productName: "Aniseed Syrup",
        supplierID: 1,
        categoryID: 2,
        quantityPerUnit: "12 - 550 ml bottles",
        unitPrice: 10,
        unitsInStock: 13,
        unitsOnOrder: 70,
        reorderLevel: 25,
        discontinued: 0,
      },
      {
        productID: 4,
        productName: "Chef Anton's Cajun Seasoning",
        supplierID: 2,
        categoryID: 2,
        quantityPerUnit: "48 - 6 oz jars",
        unitPrice: 22,
        unitsInStock: 53,
        unitsOnOrder: 0,
        reorderLevel: 0,
        discontinued: 0,
      },
      {
        productID: 5,
        productName: "Chef Anton's Gumbo Mix",
        supplierID: 2,
        categoryID: 2,
        quantityPerUnit: "36 boxes",
        unitPrice: 21.35,
        unitsInStock: 0,
        unitsOnOrder: 0,
        reorderLevel: 0,
        discontinued: 1,
      },
      {
        productID: 6,
        productName: "Grandma's Boysenberry Spread",
        supplierID: 3,
        categoryID: 2,
        quantityPerUnit: "12 - 8 oz jars",
        unitPrice: 25,
        unitsInStock: 120,
        unitsOnOrder: 0,
        reorderLevel: 25,
        discontinued: 0,
      },
      {
        productID: 7,
        productName: "Uncle Bob's Organic Dried Pears",
        supplierID: 3,
        categoryID: 7,
        quantityPerUnit: "12 - 1 lb pkgs.",
        unitPrice: 30,
        unitsInStock: 15,
        unitsOnOrder: 0,
        reorderLevel: 10,
        discontinued: 0,
      },
      {
        productID: 8,
        productName: "Northwoods Cranberry Sauce",
        supplierID: 3,
        categoryID: 2,
        quantityPerUnit: "12 - 12 oz jars",
        unitPrice: 40,
        unitsInStock: 6,
        unitsOnOrder: 0,
        reorderLevel: 0,
        discontinued: 0,
      },
      {
        productID: 9,
        productName: "Mishi Kobe Niku",
        supplierID: 4,
        categoryID: 6,
        quantityPerUnit: "18 - 500 g pkgs.",
        unitPrice: 97,
        unitsInStock: 29,
        unitsOnOrder: 0,
        reorderLevel: 0,
        discontinued: 1,
      },
      {
        productID: 10,
        productName: "Ikura",
        supplierID: 4,
        categoryID: 8,
        quantityPerUnit: "12 - 200 ml jars",
        unitPrice: 31,
        unitsInStock: 31,
        unitsOnOrder: 0,
        reorderLevel: 0,
        discontinued: 0,
      },
      {
        productID: 11,
        productName: "Queso Cabrales",
        supplierID: 5,
        categoryID: 4,
        quantityPerUnit: "1 kg pkg.",
        unitPrice: 21,
        unitsInStock: 22,
        unitsOnOrder: 30,
        reorderLevel: 30,
        discontinued: 0,
      },
      {
        productID: 12,
        productName: "Queso Manchego La Pastora",
        supplierID: 5,
        categoryID: 4,
        quantityPerUnit: "10 - 500 g pkgs.",
        unitPrice: 38,
        unitsInStock: 86,
        unitsOnOrder: 0,
        reorderLevel: 0,
        discontinued: 0,
      },
      {
        productID: 13,
        productName: "Konbu",
        supplierID: 6,
        categoryID: 8,
        quantityPerUnit: "2 kg box",
        unitPrice: 6,
        unitsInStock: 24,
        unitsOnOrder: 0,
        reorderLevel: 5,
        discontinued: 0,
      },
      {
        productID: 14,
        productName: "Tofu",
        supplierID: 6,
        categoryID: 7,
        quantityPerUnit: "40 - 100 g pkgs.",
        unitPrice: 23.25,
        unitsInStock: 35,
        unitsOnOrder: 0,
        reorderLevel: 0,
        discontinued: 0,
      },
      {
        productID: 15,
        productName: "Genen Shouyu",
        supplierID: 6,
        categoryID: 2,
        quantityPerUnit: "24 - 250 ml bottles",
        unitPrice: 15.5,
        unitsInStock: 39,
        unitsOnOrder: 0,
        reorderLevel: 5,
        discontinued: 0,
      },
      {
        productID: 16,
        productName: "Pavlova",
        supplierID: 7,
        categoryID: 3,
        quantityPerUnit: "32 - 500 g boxes",
        unitPrice: 17.45,
        unitsInStock: 29,
        unitsOnOrder: 0,
        reorderLevel: 10,
        discontinued: 0,
      },
      {
        productID: 17,
        productName: "Alice Mutton",
        supplierID: 7,
        categoryID: 6,
        quantityPerUnit: "20 - 1 kg tins",
        unitPrice: 39,
        unitsInStock: 0,
        unitsOnOrder: 0,
        reorderLevel: 0,
        discontinued: 1,
      },
      {
        productID: 18,
        productName: "Carnarvon Tigers",
        supplierID: 7,
        categoryID: 8,
        quantityPerUnit: "16 kg pkg.",
        unitPrice: 62.5,
        unitsInStock: 42,
        unitsOnOrder: 0,
        reorderLevel: 0,
        discontinued: 0,
      },
      {
        productID: 19,
        productName: "Teatime Chocolate Biscuits",
        supplierID: 8,
        categoryID: 3,
        quantityPerUnit: "10 boxes x 12 pieces",
        unitPrice: 9.2,
        unitsInStock: 25,
        unitsOnOrder: 0,
        reorderLevel: 5,
        discontinued: 0,
      },
      {
        productID: 20,
        productName: "Sir Rodney's Marmalade",
        supplierID: 8,
        categoryID: 3,
        quantityPerUnit: "30 gift boxes",
        unitPrice: 81,
        unitsInStock: 40,
        unitsOnOrder: 0,
        reorderLevel: 0,
        discontinued: 0,
      },
      {
        productID: 21,
        productName: "Sir Rodney's Scones",
        supplierID: 8,
        categoryID: 3,
        quantityPerUnit: "24 pkgs. x 4 pieces",
        unitPrice: 10,
        unitsInStock: 3,
        unitsOnOrder: 40,
        reorderLevel: 5,
        discontinued: 0,
      },
      {
        productID: 22,
        productName: "Gustaf's Knäckebröd",
        supplierID: 9,
        categoryID: 5,
        quantityPerUnit: "24 - 500 g pkgs.",
        unitPrice: 21,
        unitsInStock: 104,
        unitsOnOrder: 0,
        reorderLevel: 25,
        discontinued: 0,
      },
      {
        productID: 23,
        productName: "Tunnbröd",
        supplierID: 9,
        categoryID: 5,
        quantityPerUnit: "12 - 250 g pkgs.",
        unitPrice: 9,
        unitsInStock: 61,
        unitsOnOrder: 0,
        reorderLevel: 25,
        discontinued: 0,
      },
      {
        productID: 24,
        productName: "Guaraná Fantástica",
        supplierID: 10,
        categoryID: 1,
        quantityPerUnit: "12 - 355 ml cans",
        unitPrice: 4.5,
        unitsInStock: 20,
        unitsOnOrder: 0,
        reorderLevel: 0,
        discontinued: 1,
      },
      {
        productID: 25,
        productName: "NuNuCa Nuß-Nougat-Creme",
        supplierID: 11,
        categoryID: 3,
        quantityPerUnit: "20 - 450 g glasses",
        unitPrice: 14,
        unitsInStock: 76,
        unitsOnOrder: 0,
        reorderLevel: 30,
        discontinued: 0,
      },
      {
        productID: 26,
        productName: "Gumbär Gummibärchen",
        supplierID: 11,
        categoryID: 3,
        quantityPerUnit: "100 - 250 g bags",
        unitPrice: 31.23,
        unitsInStock: 15,
        unitsOnOrder: 0,
        reorderLevel: 0,
        discontinued: 0,
      },
      {
        productID: 27,
        productName: "Schoggi Schokolade",
        supplierID: 11,
        categoryID: 3,
        quantityPerUnit: "100 - 100 g pieces",
        unitPrice: 43.9,
        unitsInStock: 49,
        unitsOnOrder: 0,
        reorderLevel: 30,
        discontinued: 0,
      },
      {
        productID: 28,
        productName: "Rössle Sauerkraut",
        supplierID: 12,
        categoryID: 7,
        quantityPerUnit: "25 - 825 g cans",
        unitPrice: 45.6,
        unitsInStock: 26,
        unitsOnOrder: 0,
        reorderLevel: 0,
        discontinued: 1,
      },
      {
        productID: 29,
        productName: "Thüringer Rostbratwurst",
        supplierID: 12,
        categoryID: 6,
        quantityPerUnit: "50 bags x 30 sausgs.",
        unitPrice: 123.79,
        unitsInStock: 0,
        unitsOnOrder: 0,
        reorderLevel: 0,
        discontinued: 1,
      },
      {
        productID: 30,
        productName: "Nord-Ost Matjeshering",
        supplierID: 13,
        categoryID: 8,
        quantityPerUnit: "10 - 200 g glasses",
        unitPrice: 25.89,
        unitsInStock: 10,
        unitsOnOrder: 0,
        reorderLevel: 15,
        discontinued: 0,
      },
    ],
  },
  {
    name: "Large Dataset Example",
    query:
      "SELECT transaction_id, customer_id, product_id, transaction_date, amount\nFROM transactions\nWHERE transaction_date >= '2023-01-01'\nORDER BY transaction_date DESC;",
    results: Array.from({ length: 100 }, (_, i) => ({
      transaction_id: 10000 + i,
      customer_id: Math.floor(Math.random() * 1000) + 1,
      product_id: Math.floor(Math.random() * 500) + 1,
      transaction_date: new Date(2023, Math.floor(i / 8), (i % 30) + 1)
        .toISOString()
        .split("T")[0],
      amount: Number.parseFloat((Math.random() * 1000 + 50).toFixed(2)),
    })),
  },
];
